name: Build Multi-Language Version

on:
  workflow_dispatch:
  push:
    paths:
      - 'filaments_*/*.json'

jobs:
  build-multi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install check-jsonschema

      - name: Validate Filaments
        run: |
          for dir in filaments_*/; do
            for file in "$dir"*.json; do
              check-jsonschema --schemafile filaments.schema.json "$file"
            done
          done

      - name: Compile Database and Generate HTMLs
        run: python scripts/compile_lang.py

      - name: Deploy Site
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: .
