name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Prepare build environment
        run: |
          rm -rf public
          mkdir public

      - name: Build multilingual JSON
        run: |
          LANG_DIRS=$(find . -maxdepth 1 -type d -name 'filaments_*' -printf '%f\n')
          
          if [ -d "filaments" ]; then
            cp -r filaments filaments_original
          fi
          
          for LANG_DIR in $LANG_DIRS; do
            LANG=${LANG_DIR#filaments_}
            
            rm -rf filaments
            cp -r "$LANG_DIR" filaments
            
            python3 scripts/compile_filaments.py
            
            mkdir -p "public/$LANG"
            mv filaments.json "public/$LANG/filaments.json"
          done
          
          rm -rf filaments
          if [ -d "filaments_original" ]; then
            mv filaments_original filaments
          fi

      - name: Generate language-specific index.html
        run: |
          for LANG_DIR in public/*; do
            if [ -d "$LANG_DIR" ]; then
              LANG=$(basename "$LANG_DIR")
              # Ersetze {{LANG}} im Template durch den Sprachcode
              sed "s/{{LANG}}/$LANG/g" templates/template.html > "$LANG_DIR/index.html"
            fi
          done

      - name: Generate HTML files
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}  # Setzt den Repository-Namen
        run: python3 scripts/translate_html.py

      - name: Copy global assets
        run: |
          cp styles.css public/

      - name: Verify artifact content
        run: |
          echo "Struktur des public-Ordners:"
          find public -type f -print
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
