name: Translate Filament Names

on:
  workflow_dispatch:    # Manuelles Auslösen über die GitHub-Oberfläche
  push:
    paths:
      - 'filaments/*.json'   # Automatischer Start bei Änderungen an den Quelldateien
  schedule:
    - cron: '0 3 * * 1'  # Jeden Montag um 03:00 UTC
   

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install deep-translator pyyaml

      - name: Ensure filaments_de exists
        run: mkdir -p filaments_de

      - name: Run translation script
        run: |
          python scripts/translate_filaments.py

      -- name: Commit and push translations
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           if ls filaments_de/*.json 1> /dev/null 2>&1 || [ -f filaments_de/translation_dict.json ]; then
             git add filaments_de/*.json filaments_de/translation_dict.json
             git commit -m "Automatische Übersetzung der Filamentnamen (de)" || echo "No changes to commit"
             git push || echo "Nothing to push"
           else
             echo "Keine neuen Dateien zum Committen."
           fi


